apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: voting-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: votingacr.azurecr.io/voting-backend:0781c31136b109c00fb4461174d0d68417bf7173
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: PORT
              value: "5000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /votes
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /votes
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
